export const SET_PRODUCTS = 'products/setProducts'
export const SET_USER = 'user/setUser'
export const SET_CREATE = 'create/setCreate'
export const SET_UPDATE = 'update/setUpdate'
export const SET_DELETE = 'delete/setDelete'
export const SET_LOADING = 'loading/setLoading'